# Generated by Django 4.1 on 2022-09-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_movimentacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='discriminacao',
            field=models.TextField(blank=True, null=True, verbose_name='Discriminação'),
        ),
    ]
